### ISSUE TITLE
Aligner might get stuck when there is a word that appears consecutively

### ISSUE THREAD

**Issue by Ar770** [CAMeL-Lab/ced_word_alignment#1]
Thank you for the great work.
I noticed that for words that appear consecutively, the aligner might get stuck.
For example:
gold = 'אמרתם מה שאני אבוא לקחת אותך מהבית'
hypo = 'אמרתי אמרתי להם מה אתה רוצה שאני אבוא אקח אותך מהבית לבוא לקחת אותך מהבית'
The only way to make the aligner work, was by removing the first word that is repeated twice in the hypo (אמרתי).
Just letting you know, maybe there is a simple solution.
Thank you!

**Comment by Ar770** [comment]
This is the output when the first word is omitted:
SOURCE	TARGET
אמרתי להם	אמרתם
מה אתה רוצה	מה
שאני	שאני
אבוא אקח אותך מהבית לבוא	אבוא
לקחת	לקחת
אותך	אותך
מהבית	מהבית

**Comment by owo** [comment]
The issue is now fixed. You'll need to reinstall the dependencies though.
